### ISSUE TITLE
Schematron : relative URI handling

### ISSUE THREAD

**Issue by jimetevenard** [xspec/xspec-maven-plugin-1#22]
## Relative URIs in Schematron files

Being tested via an XSpec, Schematron files are compiled to an XSLT using the Skeleton implementation.
This XSLT is serialized to the report directory in `target/` and executed from there.

Unfortunately, having some `<xsl:include href="relative/uri" />` in the schematron file leads to an error, because, in such a case, the URI is relative to the original Schematron file.

*NB : Schematron's native imports (such as `<sch:extends href="..." />` are not impacted, because they are resolved earlier in the Skeleton process.*

## External ressources in the Xspec file

The same problem exists with external references in the XSpec :  
e.g. `<x:context href="some/relative/ref" select="/doc/body/p[1]"/>`

When testing a Schematron, the XSpec Maven plugin [generates a *Schematron-specific* "compiled" XSpec file](https://github.com/xspec/xspec-maven-plugin-1/blob/c1bf537fc09c2fb05bbab2a510f6f0cd521e4251/src/main/java/uk/org/adamretter/maven/XSpecMojo.java#L675), in a distinct directory.

So the following case 

```
<x:scenario label=" ... ">
   <x:context href="relative/uri"/>
   ...
</x:scenario>
```
Leads to an error because `relative/uri` is relative to the actual XSpec file.

## The solution I suggest

I've introduced an XSLT transformation step to make the URIs absolutes
* **In the compiled Schematron** - resolving URIs against the actual source Schematron file
* **In the Schmetron-specific generated XSpec** - resolving URIs against the actual XSpec file

Additionally, I've done some refacto in the execution/reporting process to take account of this double-XSpec-file case.

**Comment by AirQuick** [comment]
Though this issue is getting old, I came across it just now. So, I'm updating it for the record.

> ## Relative URIs in Schematron files

Maybe fixed by xspec/xspec#679 (will be included in XSpec v1.5.0)

> ## External ressources in the Xspec file

Maybe fixed by xspec/xspec#545 and xspec/xspec#549 (included in XSpec v1.4.0)

**Comment by cmarchand** [comment]
@jimetevenard  : could you check this is solved with 2.0.0-RC6 release ?

**Comment by jimetevenard** [comment]
Hi @cmarchand ,

I tried to reproduce this in this test repository : https://github.com/jimetevenard/xspec-maven-plugin-issue-22, but I did not even manage to make it work with a simple regular schematron file (without any includes).

The [unique XSpec test](https://github.com/jimetevenard/xspec-maven-plugin-issue-22/blob/master/src/test/xspec/check-attrs.xspec) in this repo : 
- **works** in OXygen
- **works** with previous release 2.0.0-RC5
- **Fails** with 2.0.0-RC6 release (logs above)

```
$ git clone https://github.com/jimetevenard/xspec-maven-plugin-issue-22.git
$ cd xspec-maven-plugin-issue-22

$ mvn -v
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T20:41:47+02:00)
Maven home: D:\apps\apache-maven-3.6.0
Java version: 1.8.0_191, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk1.8.0_191\jre
Default locale: fr_FR, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"


$ mvn xspec:run-xspec
[INFO] Scanning for projects...
[INFO]
[INFO] -------------< labo.jim:test-xspec-maven-plugin-issue-22 >--------------
[INFO] Building test-xspec-maven-plugin-issue-22 1.00.00-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- xspec-maven-plugin:2.0.0-RC6:run-xspec (default-cli) @ test-xspec-maven-plugin-issue-22 ---
[INFO] URI resolver Ok
[INFO] Found 1 XSpecs...
[INFO] Processing XSpec: D:\DEV\xspec-maven-plugin\issue-22\src\test\xspec\check-attrs.xspec
[INFO] Copying resource files referenced from XSpec for Schematron
file:/D:/DEV/xspec-maven-plugin/issue-22/src/test/xspec/check-attrs.xspec
$callers.uris=

file:/D:/DEV/xspec-maven-plugin/issue-22/src/main/sch/check-attrs.sch
$callers.uris=

file:/D:/DEV/xspec-maven-plugin/issue-22/src/test/samples/foo.xml
$callers.uris=

file:/D:/DEV/xspec-maven-plugin/issue-22/src/test/samples/foo-valid.xml
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.397 s
[INFO] Finished at: 2020-04-16T16:30:16+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.xspec.maven:xspec-maven-plugin:2.0.0-RC6:run-xspec (default-cli) on project test-xspec-maven-plugin-issue-22: Some XSpec tests failed or were missed! -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

file:/D:/DEV/xspec-maven-plugin/issue-22/src/main/sch/check-attrs.sch
$callers.uris=

file:/D:/DEV/xspec-maven-plugin/issue-22/src/test/samples/foo.xml
$callers.uris=

file:/D:/DEV/xspec-maven-plugin/issue-22/src/test/samples/foo-valid.xml
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.822 s
[INFO] Finished at: 2020-04-16T16:29:03+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.xspec.maven:xspec-maven-plugin:2.0.0-RC6:run-xspec (default) on project test-xspec-maven-plugin-issue-22: Some XSpec tests failed or were missed! -> [Help 1]
```

Running the full `mvn test` cycle fails as well

**Comment by cmarchand** [comment]
Solved by commit [#3598bf7](https://github.com/xspec/xspec-maven-plugin-1/commit/3598bf73eaa06a577eaa10f3440bec5f93345dfe).
Available in release [2.0.0-RC7](https://repo1.maven.org/maven2/io/xspec/maven/xspec-maven-plugin/2.0.0-RC7/)

**Comment by jimetevenard** [comment]
@cmarchand, [the bug above](https://github.com/xspec/xspec-maven-plugin-1/issues/22#issuecomment-614692436) is fixed in 2.0.0-RC7.

But **I'm still reproducing the [initial problem](https://github.com/xspec/xspec-maven-plugin-1/issues/22#issue-369196869) of this issue** : 

> Unfortunately, having some `<xsl:include href="relative/uri" />` in the schematron file leads to an error, because, in such a case, the URI is relative to the original Schematron file.
> 
> _NB : Schematron's native imports (such as `<sch:extends href="..." />` are not impacted, because they are resolved earlier in the Skeleton process._

Cf. the last commit of my test case : https://github.com/jimetevenard/xspec-maven-plugin-issue-22/commit/9a26747a068527d6b9e229a147fc1d789615a936

**Comment by AirQuick** [comment]
> > ## Relative URIs in Schematron files
> 
> Maybe fixed by [xspec/xspec#679](https://github.com/xspec/xspec/pull/679) (will be included in XSpec v1.5.0)

This fix wasn't included in XSpec v1.5.0 due to conflict with Oxygen's release schedule.
It surely is included in v1.6.0 which is going to be released this weekend.

The fix is a [dynamic patch](https://github.com/xspec/xspec/blob/f1c1aaff09068dffb45277cd45019395af308d9e/src/schematron/patch-step3.xsl#L33-L47) which overrides the Schematron skeleton step 3 (`iso_svrl_for_xslt2.xsl`) partially at run time. This runtime overriding is possible in XSpec command line and XSpec Ant, because the command line and Ant do not run `iso_svrl_for_xslt2.xsl` directly. They run  `iso_svrl_for_xslt2.xsl` via a wrapper stylesheet ([`SCH_STEP3_WRAPPER`](https://github.com/xspec/xspec/blob/f1c1aaff09068dffb45277cd45019395af308d9e/bin/xspec.sh#L315) in the command line or [`xspec.schematron.preprocessor.step3.wrapper`](https://github.com/xspec/xspec/blob/f1c1aaff09068dffb45277cd45019395af308d9e/build.xml#L281-L283) in Ant) generated at run time.

So, to be benefited from the fix, the Maven plugin would probably need to use XSpec v1.6.0 and do the same steps as the command line and Ant. (Note: To enable the fix, `ACTUAL-PREPROCESSOR-URI` parameter should _not_ be set when generating the wrapper stylesheet.)
